export const branches = [
    "Aeronautical Engineering",
    "Aerospace Engineering",
    "Automobile Engineering",
    "Biomedical Engineering",
    "Biotechnology Engineering",
    "Chemical Engineering",
    "Ceramic Engineering",
    "Civil Engineering",
    "Computer Science Engineering",
    "Communications Engineering",
    "Construction Engineering",
    'Electrical Engineering',
    "Electronics Engineering",
    "Electronics & Communication Engineering",
    "Engineering Design",
    "Engineering Physics",
    "Environmental Engineering",
    "Industrial Engineering",
    "Marine Engineering",
    "Mechanical Engineering",
    "Mechatronics Engineering",
    "Metallurgical Engineering",
    "Mining Engineering",
    "Naval Architechture and Ocean Engineering",
    "Petroleum Engineering",
    "Power Engineering",
    "Production Engineering",
    "Robotics Engineering",
    "Structural Engineering",
    "Transportation Engineering",
    "Telecommunication Engineering",
    "Textile Engineering",
    "Tool Engineering",
    "Other"
]